const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../../..'),base='art-source/six-gen',read=p=>JSON.parse(fs.readFileSync(path.resolve(ROOT,p),'utf8').replace(/^\uFEFF/,'')),write=(p,x)=>fs.writeFileSync(path.resolve(ROOT,p),JSON.stringify(x,null,2));
const profiles=read(base+'/contracts/stage-profile.snapshot.json'),old=require(path.join(ROOT,'src/art-manifest.js')).ART_RIGS;
const packages=Object.fromEntries(['pop','cup','ship','logistics','scene','ui'].map(p=>[p,read(base+'/'+p+'/assembly.json')]));
const generationStationRigs=[];for(let g=1;g<=6;g++)for(const s of ['pop','cup','ship']){let rig;if(g===1)rig=old[{pop:'popMachine',cup:'cupMachine',ship:'shipMachine'}[s]];else rig=packages[s].rigs.find(r=>(r.generationUse||[]).includes(g)&&r.stationId===s);if(!rig)throw Error('Missing '+s+' G'+g);generationStationRigs.push({generation:g,stationId:s,rig});}
write(base+'/integration/assembly.json',{contractVersion:'six-gen-art-1.0',scope:'synthetic-art-only; not runtime configuration',coordinates:'Each rig retains its own size/pixel canvas. Sprite scaling is uniform, never reinterpret old coordinate spaces.',generationStationRigs,logistics:packages.logistics,scene:packages.scene,ui:packages.ui,packaging:read('art-source/batch-1/core/assembly.json')});
write(base+'/integration/generation-configurations.json',read(base+'/qa/scene-configurations.json'));
const planned=read('art-source/six-generation-20260910/input-plan/IAA_Six_Generation_Art_Plan/asset-candidates.json'),manifest=read(base+'/integration/manifest.json'),newIds=new Set(manifest.assets.filter(a=>a.reuseSource===null).map(a=>a.id));
function replacement(id){if(/^machine_pop_.*_front$/.test(id))return['machine_pop_front'];if(/^machine_cup_.*_front$/.test(id))return['machine_cup_front'];if(/^machine_ship_.*_front$/.test(id))return['machine_ship_front'];return{machine_cup_double_carrier:['product_double_tray'],machine_cup_socket_cover:['machine_pop_socket_cover'],conveyor_bridge_back:['conveyor_down_left','conveyor_down_right'],conveyor_bridge_front:['conveyor_front_left','conveyor_front_right'],input_ship_collar:['input_cup_collar'],factory_room_extension:['factory_room'],machine_ship_wide_head:['machine_ship_head']}[id]||[];}
const decisions=planned.assets.map(a=>({id:a.id,owner:a.owner,conditional:a.conditional,status:newIds.has(a.id)?'EXPORTED':a.conditional?'NOT_NEEDED_AFTER_REUSE_REVIEW':'REPLACED_BY_REUSE',replacements:replacement(a.id),evidence:newIds.has(a.id)?base+'/integration/manifest.json':base+'/'+({A1:'pop',A2:'cup',A3:'ship',A4:'logistics',A5:'ui',A6:'scene'}[a.owner])+'/assembly.json'}));
if(decisions.some(d=>d.status!=='EXPORTED'&&!d.replacements.length))throw Error('Unresolved candidate');write(base+'/integration/candidate-resolution.json',{baseCandidates:39,conditionalCandidates:1,newIndependentPng:24,reuseResolved:15,conditionalNotNeeded:1,decisions});
const budget=read(base+'/integration/budget-report.json');
fs.writeFileSync(path.resolve(ROOT,base+'/README.md'),`# IAA 六代美术资源交付\n\n本轮只制作与验收独立美术资源，未接入游戏代码，未修改正式资源清单、数值或存档，也未构建或发布。\n\n## 先看这里\n\n- 新资源总览：reports/gallery/contact-sheet.png\n- 独立画廊：reports/gallery/index.html\n- 最终 PNG：integration/exports/\n- 总清单、来源及装配：integration/manifest.json、provenance.json、assembly.json\n- 六代各 entry/upgraded 两态、两视口：qa/previews/g01-entry-390x844.png 等 24 张。\n- UI 14 状态总览：reports/ui-states/ui-state-contact.png；两视口共 28 张状态页。\n- 仓位与设备状态：qa/previews/warehouse-48-fixture-contact.png、machine-54-state-contact.png；真实可达性说明在 qa/。\n\n## 交付数量\n\n24 张新增独立 PNG：爆锅 5、装杯 4、出货 3、物流 6、UI 3、场景 3。其中货架前缘由新原图精确拆层，未重复生图。\n60 张既有资源复用，最终共 84 张唯一 PNG。39 个基础候选中，24 个导出、15 个由合格共享件替代；1 个条件宽压头经复用检查无需新增。候选逐项去向见 integration/candidate-resolution.json。\n18 个代际工位配置、12 套代际设备组合；扩建前后保留安装数和批次量差异，空槽使用盖板。所有配置与预览明确为 synthetic-art-only。\n\n## 体积\n\n最终 PNG 合计 ${budget.allUniquePngBytes.toLocaleString('en-US')} B（${(budget.allUniquePngBytes/1048576).toFixed(2)} MiB）；RGBA 基础解码估算 ${budget.allRgbaBytes.toLocaleString('en-US')} B（${(budget.allRgbaBytes/1048576).toFixed(2)} MiB）。第一代候选依赖并集 ${budget.commonPlusGenBytes[0].pngBytes.toLocaleString('en-US')} B，三个内部预算目标均通过。此处不含原图/预览/ZIP体积，不等于GPU或进程内存。\n\n## 原图与制作记录\n\n内置 image_gen 生成；准确提示词、参考 SHA、原图及失败版本在各包 sources/、prompts 与 provenance 中。源图保持原尺寸；导出采用等比裁切/缩小和有监督 PNG 色彩量化。正式旧图不变。kernel_a 候选增加透明边距；kernel_b 与禁用按钮因量化影响边缘而保留原 PNG。\n\n最终以 integration/manifest.json 中 file 与 SHA 为准。各包 exports/ 是制作候选，体积不同但坐标保持一致。integration/common 是共享资源优化步骤，最终发布候选统一在 integration/exports。\n\n## 验证边界\n\n交付报告见 reports/delivery-verification.json 和 qa/ 最终静态验收报告。PNG签名、尺寸、真实alpha、边缘、SHA、源路径和正式文件保护均实测。预览不是运行截图；界面状态为美术表达。构建、经济回归、真实点击/拖拽、防重复购买、实际异步进度、资源加载与真机均未执行（NOT_RUN）。本轮不代表 INTEGRATED 或 VERIFIED_RUNTIME。\n\n本地画廊相对链接与脚本语法已核验；自动浏览器交互未运行。可直接查看PNG交付。制作辅助脚本只位于本美术目录，不属于正式游戏代码。\n`);
console.log(JSON.stringify({generationStationRigs:generationStationRigs.length,candidates:decisions.length,resolved:decisions.every(d=>d.status==='EXPORTED'||d.replacements.length)}));
