const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/chenweilun/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp/dist/index.cjs');
const ROOT=path.resolve(__dirname,'../../..'),base='art-source/six-gen/integration/common';fs.mkdirSync(path.join(ROOT,base,'exports'),{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(path.resolve(ROOT,p),'utf8').replace(/^\uFEFF/,'')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(path.resolve(ROOT,p))).digest('hex');
async function main(){const m=read('assets/art/manifest.json'),r=read('art-source/six-gen/qa/compression-report.json').presets.find(p=>p.preset.id==='compact256'),entries=[],recipe=[];
for(const row of r.rows){const a=m.entries.find(x=>x.id===row.id),dst=path.join(ROOT,base,'exports',row.id+'.png');const preserve=['product_kernel_b','ui_button_disabled'].includes(row.id);if(preserve)fs.copyFileSync(path.join(ROOT,a.path),dst);else if(row.id==='product_kernel_a')await sharp(path.join(ROOT,row.file)).extend({top:2,bottom:2,left:2,right:2,background:{r:0,g:0,b:0,alpha:0}}).png({palette:true,colours:256,quality:92,compressionLevel:9}).toFile(dst);else fs.copyFileSync(path.join(ROOT,row.file),dst);
const mm=await sharp(dst).metadata(),pad=row.id==='product_kernel_a'?2:0;
const anc=a.anchor||[a.width/2,a.height];const point=Array.isArray(anc)?anc:[anc.x,anc.y];const anchor=[point[0]*(preserve?a.width:row.width)/a.width+pad,point[1]*(preserve?a.height:row.height)/a.height+pad];
entries.push({id:a.id,status:'EXPORTED',category:a.id.startsWith('ui_')?'ui':a.id.startsWith('product_')?'product':a.id.startsWith('fx_')?'fx':a.id.startsWith('machine_')?'machine':'scene',stageUse:[1,2,3,4,5,6],file:base+'/exports/'+a.id+'.png',width:mm.width,height:mm.height,anchor,sourceFile:a.path,sha256:hash(dst),provenanceRef:base+'/provenance.json',reuseSource:a.path,alphaMode:mm.hasAlpha?'RGBA':'opaque-background'});
recipe.push({id:a.id,originalFile:a.path,originalSha256:hash(a.path),inputCandidate:preserve?a.path:row.file,outputFile:base+'/exports/'+a.id+'.png',originalSize:[a.width,a.height],sourceRect:[0,0,a.width,a.height],outputSize:[mm.width,mm.height],method:preserve?'preserve original PNG byte-for-byte: palette candidate failed exact alpha edge test':'compact256: products/icons native, other sprites uniform 0.75; palette256; alpha retained',extraPadding:pad,bytes:fs.statSync(dst).size,rgbaBytes:mm.width*mm.height*4});
}
const b={schemaVersion:1,contractVersion:'six-gen-art-1.0',baseCommit:'14310d34e882969208bb7583c5e0c8442bfc3aee',owner:'A0'};
fs.writeFileSync(path.join(ROOT,base,'manifest.fragment.json'),JSON.stringify({...b,assets:entries},null,2));fs.writeFileSync(path.join(ROOT,base,'export-recipe.json'),JSON.stringify({...b,operations:recipe},null,2));fs.writeFileSync(path.join(ROOT,base,'provenance.json'),JSON.stringify({...b,kind:'existing accepted library with candidate-only optimization',evidence:'art-source/six-gen/qa/compression-report.json',operations:recipe},null,2));console.log(JSON.stringify({count:entries.length,bytes:recipe.reduce((s,e)=>s+e.bytes,0),rgbaBytes:recipe.reduce((s,e)=>s+e.rgbaBytes,0),kernelRepair:'2px padding; original untouched'}));}
main().catch(e=>{console.error(e);process.exitCode=1});
