'use strict';
// Layer-only artwork composition. No game imports, screenshot tracing or bitmap painting.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const layout=read(path.join(__dirname,'scene-layout.json'));
const sources=Object.fromEntries(Object.entries(layout.sources).map(([key,file])=>[key,read(path.join(root,file))]));
const assets={};
for(const category of ['scene','machines','products'])for(const file of fs.readdirSync(path.join(root,'assets/art',category)).filter(f=>f.endsWith('.png'))){const bytes=fs.readFileSync(path.join(root,'assets/art',category,file));assets[path.basename(file,'.png')]={width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),data:'data:image/png;base64,'+bytes.toString('base64')};}
const used=new Set();let serial=0;
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const group=(x,y,s,svg)=>`<g transform="translate(${x} ${y}) scale(${s})">${svg}</g>`;
function image(id,r,flip=false){if(!assets[id])throw Error('Missing asset '+id);used.add(id);const el=`<use href="#asset-${id}" x="${r[0]}" y="${r[1]}" width="${r[2]}" height="${r[3]}"/>`;return flip?`<g transform="translate(${2*r[0]+r[2]} 0) scale(-1 1)">${el}</g>`:el;}
const part=p=>image(p.id,p.rect,p.flipX);
function clip(points,svg){if(!points)return svg;const id='scene-clip-'+serial++;return `<defs><clipPath id="${id}"><polygon points="${points.map(p=>p.join(',')).join(' ')}"/></clipPath></defs><g clip-path="url(#${id})">${svg}</g>`;}
function cup(progress=1){const c=sources.batch0.cupProduct;const r=[...c.fill.rect];r[1]+=c.fillTravel[1]*(1-progress);return part(c.empty)+(progress>0?clip(c.fillClip,image(c.fill.id,r)):'');}
function cupAt(r,progress=1){return group(r[0],r[1],r[2]/sources.batch0.cupProduct.size[0],cup(progress));}
function packageRig(name,closed=false){const r=sources.packaging[name],layers=[];for(const p of r.parts){if(p.state==='closed'&&!closed)continue;layers.push({layer:p.layer,svg:p.clip?clip(r[p.clip],part(p)):part(p)});}if(!closed)for(const slot of r.slots)layers.push({layer:slot.layer,svg:clip(r.contentClip,cupAt(slot.rect))});return layers.sort((a,b)=>a.layer-b.layer).map(p=>p.svg).join('');}
function bulk(quantity,capacity=12){const b=sources.batch0.bulkBuffer;let content='';const ratio=quantity/capacity;if(quantity>0&&quantity<4){for(let i=0;i<quantity;i++)content+=image(i%2?'product_kernel_b':'product_kernel_a',[190+i*40,171+i*15,50,i%2?48.4375:47.65625]);}else if(quantity>0){const count=Math.ceil(ratio*24);for(let i=0;i<count;i++){const row=Math.floor(i/6),col=i%6,id=i%2?'product_kernel_b':'product_kernel_a';content+=image(id,[157+col*45-row*25,145+col*18+row*25-b.fillLift*ratio,56,id.endsWith('_a')?53.375:54.25]);}}return part(b.back)+clip(b.contentClip,content)+part(b.front);}
function cupsBuffer(quantity,capacity=12){const b=sources.machinery.cupsBuffer;const count=quantity===0?0:quantity<3?quantity:Math.max(1,Math.ceil(quantity/capacity*b.content.representativeLimit));const content=b.content.slots.slice(0,count).map(r=>cupAt(r)).join('');return b.layers.filter(p=>p.layer<30).map(part).join('')+clip(b.contentClip,content)+b.layers.filter(p=>p.layer>=30).map(part).join('');}
function machine(name,state){if(name==='cupMachine'){const c=sources.batch0.cupMachine;return part(c.body)+part(c.head)+cupAt(c.cup.rect,state==='empty'?0:1)+part(c.front);}const r=sources.machinery[name];let content='';if(name==='popMachine'&&state!=='empty')content=clip(r.contentClip,image('product_cup_fill',r.content.exampleFill));if(name==='shipMachine'&&state!=='empty'){if(state==='box'||state==='double'){const p=r.content.packageRigs.find(p=>p.rig===(state==='box'?'fourCupBox':'doubleTray'));content=group(p.translate[0],p.translate[1],p.scale,packageRig(p.rig));}else content=cupAt(r.content.singleCup);}return r.layers.filter(p=>p.layer<30).map(part).join('')+content+r.layers.filter(p=>p.layer>=30).map(part).join('');}
function belt(node){const r=sources[node.source][node.rig];let cargo='';for(const t of [.38,.68]){const x=r.input[0]+(r.output[0]-r.input[0])*t,y=r.input[1]+(r.output[1]-r.input[1])*t;if(node.cargo==='cups'){const w=14/node.scale;cargo+=cupAt([x-w/2,y-w*121/104,w,w*128/104]);}else{const w=6/node.scale;cargo+=image(t<.5?'product_kernel_a':'product_kernel_b',[x-w/2,y-w,w,w*(t<.5?61:62)/64]);}}const layers=r.layers||[r.back,r.front];return layers.filter(p=>p.layer<30).map(part).join('')+cargo+layers.filter(p=>p.layer>=30).map(part).join('');}
const placements={};
for(const node of layout.nodes){const rig=sources[node.source][node.rig];let xy=node.translate;if(node.attach){const prior=placements[node.attach.from],from=prior.rig[node.attach.fromPort],to=rig[node.attach.toPort];xy=[prior.xy[0]+from[0]*prior.node.scale-to[0]*node.scale,prior.xy[1]+from[1]*prior.node.scale-to[1]*node.scale];}placements[node.id]={node,rig,xy,anchorY:xy[1]+rig.anchor[1]*node.scale};}
const joins=layout.nodes.filter(n=>n.attach).map(n=>{const p=placements[n.id],prior=placements[n.attach.from],a=prior.rig[n.attach.fromPort],b=p.rig[n.attach.toPort];const from=[prior.xy[0]+a[0]*prior.node.scale,prior.xy[1]+a[1]*prior.node.scale],to=[p.xy[0]+b[0]*n.scale,p.xy[1]+b[1]*n.scale];return {from:n.attach.from,to:n.id,distance:Math.hypot(from[0]-to[0],from[1]-to[1])};});
if(joins.some(j=>j.distance>.001))throw Error('Port alignment failed');
const text=(value,x,y,size=18,fill='#315d5a',weight=500,anchor='start')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${fill}" font-weight="${weight}" text-anchor="${anchor}">${esc(value)}</text>`;
const card=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="16" fill="#fffaf0" stroke="#d6ded2"/>`;
function scene(){let svg=image(layout.scene.background.id,layout.scene.background.rect)+image(layout.scene.window.id,layout.scene.window.rect);const ordered=Object.values(placements).sort((a,b)=>(a.node.kind==='belt'?0:1)-(b.node.kind==='belt'?0:1)||a.anchorY-b.anchorY);for(const p of ordered){const n=p.node,content=n.kind==='belt'?belt(n):n.rig==='bulkBuffer'?bulk(n.quantity,n.capacity):n.rig==='cupsBuffer'?cupsBuffer(n.quantity,n.capacity):machine(n.rig,n.state);svg+=group(p.xy[0],p.xy[1],n.scale,content);}for(const l of layout.labels)svg+=text(l.text,l.x,l.y,10,'#235c60',750);return svg;}
let body=`<rect width="${layout.sheet.width}" height="${layout.sheet.height}" fill="#eee9dd"/><g font-family="Microsoft YaHei, Noto Sans CJK SC, sans-serif">`;
body+=text('批次 1 · 三工位与两仓静态装配',30,47,30,'#18565b',750)+text('独立 PNG 按装配锚点等比叠放；Z 字生产顺序与遮挡校对，未接入游戏。',31,78,17,'#6b7c71');
for(const v of layout.viewports){const s=v.logicalWidth/layout.scene.width*v.exportScale;body+=text(v.name,v.translate[0],v.translate[1]-15,19,'#315d5a',750);body+=card(v.translate[0]-1,v.translate[1]-1,v.logicalWidth*v.exportScale+2,v.logicalHeight*v.exportScale+2);body+=group(v.translate[0],v.translate[1],s,scene());}
body+=text('爆锅 → 待装 → 装杯 → 待发 → 出货',940,1141,18,'#315d5a',750)+text('同一装配缩放；内容与数量标签分开。',940,1169,16,'#6b7c71');
body+=image('factory_door',[947,1189,78.8,102.4])+text('独立门口部件',1048,1220,18,'#315d5a',750)+text('原图为左墙方向，另栏保留。',1048,1248,16,'#6b7c71')+text('不将其强行放到右墙。',1048,1274,16,'#6b7c71');
body+=text('两仓状态 · 后壳 → 受裁切内容 → 前挡板',30,1370,23,'#18565b',750);
for(let row=0;row<2;row++)for(const [i,state] of layout.bufferStates.entries()){const x=30+i*392,y=1391+row*193;body+=card(x,y,372,180)+text((row?'待发':'待装')+' · '+state.label,x+16,y+27,18,'#315d5a',750)+text(state.quantity+' / '+state.capacity,x+350,y+27,17,'#687c70',650,'end');const s=.37;body+=group(x+89,y+40,s,row?cupsBuffer(state.quantity,state.capacity):bulk(state.quantity,state.capacity));}
body+=text('空仓无产品；少量仍可辨认；接近满与满仓使用有限代表物。正式数量与状态由后续接入读取。',31,1789,15,'#6b7c71');
body+='</g>';
const defs=[...used].map(id=>{const a=assets[id];return `<symbol id="asset-${id}" viewBox="0 0 ${a.width} ${a.height}" preserveAspectRatio="xMidYMid meet"><image href="${a.data}" width="${a.width}" height="${a.height}"/></symbol>`;}).join('');
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${layout.sheet.width}" height="${layout.sheet.height}" viewBox="0 0 ${layout.sheet.width} ${layout.sheet.height}"><defs>${defs}</defs>${body}</svg>`;
fs.writeFileSync(path.join(__dirname,'scene-preview.svg'),svg);
async function main(){let sharp;try{sharp=require('sharp');}catch{if(process.argv[2])sharp=require(path.resolve(process.argv[2]));}if(!sharp)throw Error('Pass installed sharp module path to also render the required PNG');await sharp(Buffer.from(svg)).png().toFile(path.join(__dirname,'scene-preview.png'));console.log(JSON.stringify({scene:[390,600],compact:[320,492.307692],sheet:[layout.sheet.width,layout.sheet.height],assets:used.size,connections:joins.length,maxPortGap:Math.max(...joins.map(j=>j.distance)),placements:Object.fromEntries(Object.entries(placements).map(([id,p])=>[id,p.xy.map(v=>Number(v.toFixed(3)))])),files:['scene-layout.json','build-scene.cjs','scene-preview.svg','scene-preview.png']},null,2));}
main().catch(error=>{console.error(error);process.exitCode=1;});
