$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$cupRoot='C:/Users/chenweilun/Documents/GitHub/IAA'
$cupDir=Join-Path $cupRoot 'art-source/six-gen/cup'
function Cup-Sha($p){(Get-FileHash -LiteralPath (Join-Path $cupRoot $p)).Hash.ToLowerInvariant()}
function Cup-Json($n,$v){$v|ConvertTo-Json -Depth 50|Set-Content -LiteralPath (Join-Path $cupDir $n) -Encoding utf8}
$cupToolFiles=@{
'cup_pair_body_v1'='exec-4ca5e008-de8b-4b75-9b6e-f76dca479b12.png';'cup_pair_body_v2'='exec-93c66d7e-3e6e-4da5-a7db-810b30778037.png';'cup_pair_body_v3'='exec-dfb53958-bbed-487c-ac39-205e5bcf5439.png';
'cup_triple_body_v1'='exec-5005c513-bd30-49e1-8937-164801e4baa1.png';'cup_triple_body_v2'='exec-d603fad9-b768-4ba1-9142-88793dc43182.png';'cup_triple_body_v3'='exec-1686a9d2-a64d-4f3b-b016-8bc535641400.png';
'cup_quad_body_v1'='exec-5da54bc5-4d1a-41ed-b634-6190d21408b9.png';'cup_quad_body_v2'='exec-49d1582e-69cb-4c0d-b93d-354a3fd8ab51.png';
'cup_hex_body_v1'='exec-fc666bd3-54be-4d19-aa97-1ab4ea37234f.png';'cup_hex_body_v2'='exec-3b8f5747-1ae0-4499-88ca-5f275666d287.png'
}
$prompts=@(Get-Content -LiteralPath (Join-Path $cupDir 'prompts.jsonl') | Where-Object {$_} | ForEach-Object {$_|ConvertFrom-Json})
$sourceAudit=@();$records=@()
foreach($p in $prompts){
 $source='art-source/six-gen/cup/sources/machine_'+$p.id+'.png';$path=Join-Path $cupRoot $source;$im=[System.Drawing.Bitmap]::FromFile($path);$bytes=[IO.File]::ReadAllBytes($path);$pass=$im.PixelFormat -eq [System.Drawing.Imaging.PixelFormat]::Format32bppArgb;$status=if($pass){'EXPORTED'}else{'REJECTED_ALPHA'}
 $sha=Cup-Sha $source;$sourceAudit+=[ordered]@{path=$source;width=$im.Width;height=$im.Height;pixelFormat=$im.PixelFormat.ToString();pngColorType=$bytes[25];pngBitDepth=$bytes[24];pngSignatureHex=([BitConverter]::ToString($bytes[0..7]));cornerAlpha=$im.GetPixel(0,0).A;sha256=$sha;bytes=$bytes.Length;status=$status};$im.Dispose()
 $refs=@($p.references|ForEach-Object {[ordered]@{path=$_;sha256=(Cup-Sha $_);role=$(if($_ -like '*sources*'){'visually inspected edit target'}else{'visually inspected style or geometry reference'})}})
 $toolPath='C:/Users/chenweilun/.codex/generated_images/01a08a03-5a57-7a41-bb30-a07ef12a784f/'+$cupToolFiles[$p.id]
 $toolSha=(Get-FileHash -LiteralPath $toolPath).Hash.ToLowerInvariant();if($toolSha -ne $sha){throw "Source copy hash mismatch $source"}
 $record=[ordered]@{id=$p.id;assetId=$p.assetId;status=$status;requestedAt=$p.requestedAt;tool='image_gen.imagegen';mode='built-in';model='unavailable';seed='unavailable';returnedImageId='unavailable';toolOutputFile=$toolPath;originalAndCopyShaMatch=$true;source=$source;sourceSha256=$sha;promptRef=('prompts.jsonl#'+$p.id);references=$refs;changeRequest=$p.changeRequest}
 $records+=$record;$p.status=$status
}
$reusePaths=@('assets/art/machines/machine_cup_body.png','assets/art/machines/machine_cup_head.png','assets/art/machines/machine_cup_front.png','assets/art/products/product_cup_empty.png','assets/art/products/product_cup_fill.png','assets/art/products/product_double_tray.png','art-source/six-gen/pop/exports/machine_pop_socket_cover.png')
$reuse=@($reusePaths|ForEach-Object {[ordered]@{path=$_;sha256=(Cup-Sha $_);decision='reference directly; no copied or renamed asset';visuallyInspected=$true}})
$prompts|ForEach-Object {$_|ConvertTo-Json -Compress -Depth 20}|Set-Content -LiteralPath (Join-Path $cupDir 'prompts.jsonl') -Encoding utf8
Cup-Json 'image-audit.json' $sourceAudit
Cup-Json 'provenance.json' ([ordered]@{schemaVersion=1;owner='A2';contractVersion='six-gen-art-1.0';baseCommit='14310d34e882969208bb7583c5e0c8442bfc3aee';referenceLock=[ordered]@{path='art-source/six-gen/references/reference-lock.json';sha256=(Cup-Sha 'art-source/six-gen/references/reference-lock.json')};styleContract=[ordered]@{path='art-source/six-gen/contracts/style-contract.json';sha256=(Cup-Sha 'art-source/six-gen/contracts/style-contract.json')};records=$records;reuseReferences=$reuse;assemblySources=@([ordered]@{path='art-source/batch-0/assembly.json';sha256=(Cup-Sha 'art-source/batch-0/assembly.json')},[ordered]@{path='art-source/batch-1/core/assembly.json';sha256=(Cup-Sha 'art-source/batch-1/core/assembly.json')});notes=@('Ten original generated PNGs preserved: four successful RGBA sources and six rejected RGB sources.','CR_ALPHA_01 authorized pair third repair from new successful transparent-output evidence. CR_ALPHA_02 authorized triple third attempt from approved RGBA reference.','No API/CLI fallback used. No model/seed or unseen reference claims invented.')})
$manifest=Get-Content -Raw -LiteralPath (Join-Path $cupDir 'manifest.fragment.json')|ConvertFrom-Json
$assembly=Get-Content -Raw -LiteralPath (Join-Path $cupDir 'assembly.json')|ConvertFrom-Json
$audit=Get-Content -Raw -LiteralPath (Join-Path $cupDir 'export-audit.json')|ConvertFrom-Json
$sizeMap=@{};foreach($a in $manifest.assets){$sizeMap[$a.id]=@($a.width,$a.height)};foreach($r in $reusePaths){$im=[System.Drawing.Bitmap]::FromFile((Join-Path $cupRoot $r));$sizeMap[[IO.Path]::GetFileNameWithoutExtension($r)]=@($im.Width,$im.Height);$im.Dispose()}
$geometryErrors=@();foreach($rig in $assembly.rigs){$parts=@($rig.layers);foreach($slot in $rig.slots){$parts+=@($slot.head,$slot.cup,$slot.front,$slot.cover)|Where-Object {$_};if($slot.packagingRect){$r=$slot.packagingRect;if([Math]::Abs(($r[2]/160)-($r[3]/154)) -gt 0.0001){$geometryErrors+="Nonuniform carrier: $($rig.id)/$($slot.id)"}}};foreach($part in $parts){if(-not $sizeMap.ContainsKey($part.id)){$geometryErrors+="Missing asset: $($part.id)";continue};$r=$part.rect;$size=$sizeMap[$part.id];if([Math]::Abs(($r[2]/$size[0])-($r[3]/$size[1])) -gt 0.0001){$geometryErrors+="Nonuniform part: $($rig.id)/$($part.id)"};if($r[0] -lt -0.1 -or $r[1] -lt -0.1 -or $r[0]+$r[2] -gt $rig.size[0]+0.1 -or $r[1]+$r[3] -gt $rig.size[1]+0.1){$geometryErrors+="Out of canvas: $($rig.id)/$($part.id)"}}}
$checks=@([ordered]@{name='Generated source files, PNG signatures, dimensions, modes and SHA';status='PASS';evidence='image-audit.json; all original/copy hashes match'},[ordered]@{name='Four export PNG alpha and padding';status='PASS';evidence='export-audit.json; RGBA, corner alpha 0, perimeter nontransparent count 0'},[ordered]@{name='Uniform transforms and rig rectangles';status=$(if($geometryErrors.Count){'FAIL'}else{'PASS'});evidence=$geometryErrors},[ordered]@{name='Empty hull shape and prohibited content';status='PASS_VISUAL';evidence='Four final hulls have 2/3/4/6 empty bays, no installed heads/cups/products/text'},[ordered]@{name='Shallow/deep/checker backgrounds';status='PASS_VISUAL';evidence='previews/*-three-backgrounds.png; final composites have no baked checkerboard or visible white halo'},[ordered]@{name='Independent heads, cup mouths and front guards';status='PASS_VISUAL';evidence='previews/*-assembly.png'},[ordered]@{name='Four/six-slot double portions and mixed old/new batch';status='PASS_STATIC_VISUAL';evidence='previews/quad-two-portion-assembly.png and hex-two-portion-assembly.png'},[ordered]@{name='Low-alpha source edge colors';status='FINAL_COMPOSITE_REVIEWED';evidence='Source alpha edges include hidden/very low-alpha cyan/blue RGB residues; originals preserved, final light/dark composites checked; no global color removal'},[ordered]@{name='Independent full-screen Gate 3 review';status='PENDING_A0_A7';evidence='QA renderer consumes assembly.json'},[ordered]@{name='Runtime integration/build/device';status='NOT_RUN';reason='User requested artwork only'})
$totalBytes=($audit|Measure-Object -Property bytes -Sum).Sum
Cup-Json 'qa-report.json' ([ordered]@{schemaVersion=1;owner='A2';contractVersion='six-gen-art-1.0';baseCommit='14310d34e882969208bb7583c5e0c8442bfc3aee';status=$(if($geometryErrors.Count){'CHANGES_REQUIRED'}else{'READY_FOR_INDEPENDENT_ART_QA'});generationStatus='10 completed calls: 4 accepted RGBA sources, 6 rejected RGB sources';exportStatus='4 exported empty hull PNGs';assemblyStatus='5 distinct rigs provide six-generation use, with 1/2/3/4/6 independently placed heads';counts=[ordered]@{generatedSourceFiles=10;successfulSourceFiles=4;rejectedSourceFiles=6;exportedNewSprites=4;exportBytes=$totalBytes;reusedPngReferences=7;cancelledByReuse=6};checks=$checks;unresolvedGeometryErrors=$geometryErrors;nextDependency='A0/A7 independent merged scene QA';writeBoundary='Only art-source/six-gen/cup written by A2. Official assets, code and build directories unchanged by this agent.'})
if($geometryErrors.Count){$geometryErrors|Write-Output;exit 1}
"CUP final metadata: 4 RGBA exports; $totalBytes bytes; geometry checks passed."
