const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const dir=__dirname;
const html=fs.readFileSync(path.join(dir,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
scripts.forEach((script,i)=>new vm.Script(script,{filename:`inline-script-${i+1}.js`}));
const references=[...html.matchAll(/(?:src|href)="([^"]*)"/g)].map(m=>m[1]).filter(v=>v&&!v.startsWith('#'));
const missing=[...new Set(references)].filter(v=>!fs.existsSync(path.resolve(dir,v)));
const data=JSON.parse(fs.readFileSync(path.join(dir,'gallery-data.json'),'utf8'));
const previewEvidence=data.previews.map(p=>({name:p.name,imageExists:fs.existsSync(path.resolve(dir,p.href)),evidenceExists:fs.existsSync(path.resolve(dir,p.evidence))}));
const result={checkedAt:new Date().toISOString(),javascriptSyntax:'PASS',inlineScriptCount:scripts.length,relativeReferenceCount:new Set(references).size,missingRelativeReferences:missing,allPreviewEvidencePresent:previewEvidence.every(p=>p.imageExists&&p.evidenceExists),previewEvidence,browserInteraction:'NOT_RUN_URL_SECURITY_POLICY',browserBlock:'Chrome Browser Use rejected file:// URL navigation. No indirect, localhost, alternative-browser or headless workaround attempted.',contactSheetVisualReview:'PASS: all 24 final palette PNGs visually inspected; silhouettes, style and transparency remain readable at gallery display scale.',limitations:['Browser rendering, clicks, modal and responsive UI were not executed because file:// navigation was blocked.','Static JavaScript parsing and file-link existence are not browser interaction tests.'],indexSha256:crypto.createHash('sha256').update(html).digest('hex')};
fs.writeFileSync(path.join(dir,'gallery-verification.json'),JSON.stringify(result,null,2));
const reviewPath=path.join(dir,'asset-review.json');const review=JSON.parse(fs.readFileSync(reviewPath,'utf8'));review.visualContactReview='PASS_FINAL_PALETTE';review.galleryVerification='gallery-verification.json';review.browserInteraction='NOT_RUN_URL_SECURITY_POLICY';fs.writeFileSync(reviewPath,JSON.stringify(review,null,2));
console.log(JSON.stringify({javascriptSyntax:result.javascriptSyntax,missingRelativeReferences:missing,previewEvidenceCount:previewEvidence.length,allPreviewEvidencePresent:result.allPreviewEvidencePresent,browserInteraction:result.browserInteraction}));
if(missing.length||!result.allPreviewEvidencePresent)process.exitCode=1;
