$ErrorActionPreference='Stop'
$packageRoot=$PSScriptRoot
$repoRoot=(Resolve-Path (Join-Path $packageRoot '../../..')).Path
$recipe=Get-Content -Raw (Join-Path $packageRoot 'export-recipe.json') | ConvertFrom-Json
$prompts=@(Get-Content (Join-Path $packageRoot 'prompts.jsonl') | Where-Object {$_} | ForEach-Object {ConvertFrom-Json $_})
$manifest=@();$provenance=@();$checks=@()
foreach($asset in $recipe.assets){
 $prompt=$prompts | Where-Object {$_.assetId -eq $asset.id} | Select-Object -Last 1
 $refs=@();foreach($ref in $prompt.references){$refs += [ordered]@{file=$ref;sha256=(Get-FileHash -LiteralPath (Join-Path $repoRoot $ref)).Hash.ToLower();role='actually viewed reference'}}
 $manifest += [ordered]@{id=$asset.id;status='EXPORTED';category='ui';stageUse=@(1,2,3,4,5,6);file=('art-source/six-gen/ui/'+$asset.file);width=$asset.recipe.exportSize[0];height=$asset.recipe.exportSize[1];anchor=@(($asset.recipe.exportSize[0]/2),($asset.recipe.exportSize[1]/2));sourceFile=('art-source/six-gen/ui/'+$asset.sourceFile);sha256=$asset.exportSha256;provenanceRef=('art-source/six-gen/ui/provenance.json#'+$asset.id);reuseSource=$null;alphaMode='RGBA';notes='Single shared bitmap for all generations; no baked letters, numerals or amounts.'}
 $provenance += [ordered]@{id=$asset.id;tool='image_gen.imagegen';mode='builtin';model='unavailable';seed='unavailable';resultId=$prompt.resultId;attempt=$prompt.attempt;sourceFile=$asset.sourceFile;sourceSha256=$asset.sourceSha256;exportFile=$asset.file;exportSha256=$asset.exportSha256;references=$refs;promptFile='prompts.jsonl';sourceFileTimestampUtc=(Get-Item -LiteralPath (Join-Path $packageRoot $asset.sourceFile)).LastWriteTimeUtc.ToString('o')}
 $checks += [ordered]@{id=$asset.id;pngSignature='PASS';sourceColorType=[int]([IO.File]::ReadAllBytes((Join-Path $packageRoot $asset.sourceFile)))[25];realAlpha=$asset.recipe.hasRealAlpha;alphaMin=$asset.recipe.alphaMin;alphaMax=$asset.recipe.alphaMax;alphaZero=$asset.recipe.alphaZero;exportSize=$asset.recipe.exportSize;uniformScale='PASS';padding='2 export pixels';visualNoBakedTextDigitsCurrency='PASS';visualNoCheckerboard='PASS';referenceStyle='PASS';sourceAndExportSha='PASS';bytes=(Get-Item -LiteralPath (Join-Path $packageRoot $asset.file)).Length}
}
$base='14310d34e882969208bb7583c5e0c8442bfc3aee'
[ordered]@{schemaVersion=1;contractVersion='six-gen-art-1.0';baseCommit=$base;owner='A5';assets=$manifest} | ConvertTo-Json -Depth 30 | Set-Content -LiteralPath (Join-Path $packageRoot 'manifest.fragment.json') -Encoding UTF8
[ordered]@{schemaVersion=1;contractVersion='six-gen-art-1.0';baseCommit=$base;owner='A5';referenceLock='art-source/six-gen/references/reference-lock.json';referenceLockSha256=(Get-FileHash -LiteralPath (Join-Path $repoRoot 'art-source/six-gen/references/reference-lock.json')).Hash.ToLower();assets=$provenance;rejectedAttempts=@()} | ConvertTo-Json -Depth 30 | Set-Content -LiteralPath (Join-Path $packageRoot 'provenance.json') -Encoding UTF8
[ordered]@{schemaVersion=1;contractVersion='six-gen-art-1.0';owner='A5';scope='three artwork assets only';status='LOCAL_ART_CHECKS_PASS_PENDING_A7';assets=$checks;evidence=@('alpha-three-backgrounds.png','ui-size-preview.png');executed=@('PNG colorType and real alpha','source/export SHA','mechanical crop and uniform scale','two-pixel transparent gutter','three background visual inspection','32/48/96 pixel size preview');notRun=@('full UI states and viewport screens: A0/A7','runtime integration','game build','device verification');forbiddenPathsWritten=@()} | ConvertTo-Json -Depth 30 | Write-Output
