import { readFile, writeFile, mkdir, copyFile, readdir, lstat, unlink } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';

// Only independent first-generation parts. Reference sheets, packaging for higher
// generations and unused transfer/infeed art never enter either runtime package.
export const FIRST_GENERATION_IDS = [
  'machine_pop_body', 'machine_pop_head', 'machine_pop_front',
  'machine_cup_body', 'machine_cup_head', 'machine_cup_front',
  'machine_ship_body', 'machine_ship_head', 'machine_ship_front',
  'buffer_bulk_back', 'buffer_bulk_front', 'buffer_cups_back', 'buffer_cups_front',
  'conveyor_down_right', 'conveyor_front_right', 'conveyor_down_left', 'conveyor_front_left',
  'conveyor_outfeed_back', 'conveyor_outfeed_front',
  'conveyor_transfer_back', 'conveyor_transfer_front',
  'product_kernel_a', 'product_kernel_b', 'product_cup_empty', 'product_cup_fill',
  'factory_room', 'factory_window', 'fx_sparkle',
  'ui_hud_coin', 'ui_hud_rate', 'ui_panel', 'ui_button_primary', 'ui_button_secondary',
  'ui_button_disabled', 'ui_card', 'ui_compact_bar',
  ...['coin', 'pop', 'cup', 'ship', 'settings'].map(id => 'ui_icon_' + id)
];
export const ART_SOURCE_FILES = ['assets/art/manifest.json', 'art-source/batch-0/assembly.json',
  'art-source/batch-1/machinery/assembly.json'];

function contained(root, file) {
  const resolved = path.resolve(root, file);
  if (!resolved.startsWith(path.resolve(root) + path.sep)) throw new Error('Art path outside package: ' + file);
  return resolved;
}
function normalizeRig(rig) {
  const result = { ...rig };
  result.layers = (rig.layers || Object.entries(rig).filter(([, value]) => value && value.id && value.rect)
    .map(([part, value]) => ({ part, ...value }))).map(layer => ({ ...layer }));
  // Cup occupancy comes from the actual job, never an unconditional art layer.
  if (result.cup) result.layers = result.layers.filter(layer => layer.part !== 'cup');
  if (!result.clickRegion && result.size) {
    const [w, h] = result.size;
    result.clickRegion = [[0, 0], [w, 0], [w, h], [0, h]];
  }
  return result;
}

export async function readRuntimeArt(root) {
  const [manifest, batch0, machinery] = await Promise.all(ART_SOURCE_FILES.map(async file =>
    JSON.parse(await readFile(path.join(root, file), 'utf8'))));
  const byId = new Map(manifest.entries.map(entry => [entry.id, entry]));
  const assets = {}, entries = [];
  for (const id of FIRST_GENERATION_IDS) {
    const entry = byId.get(id);
    if (!entry || !/^assets\/art\/[a-z_]+\/[a-z_]+\.png$/.test(entry.path)) throw new Error('Invalid runtime art: ' + id);
    const bytes = await readFile(contained(root, entry.path));
    if (bytes.toString('hex', 0, 8) !== '89504e470d0a1a0a' || bytes.readUInt32BE(16) !== entry.width || bytes.readUInt32BE(20) !== entry.height) {
      throw new Error('PNG dimensions/signature disagree with art manifest: ' + id);
    }
    const resource = { id, path: entry.path, width: entry.width, height: entry.height, bytes: bytes.length,
      decodedBytes: entry.width * entry.height * 4, sha256: createHash('sha256').update(bytes).digest('hex') };
    assets[id] = { ...resource, anchor: entry.anchor, source: entry.source, sourceRect: entry.sourceRect };
    entries.push(resource);
  }
  const rigs = Object.fromEntries([
    ...['cupMachine', 'cupProduct', 'bulkBuffer', 'conveyorRight', 'conveyorLeft'].map(id => [id, normalizeRig(batch0[id])]),
    ...['popMachine', 'shipMachine', 'cupsBuffer', 'conveyorOutfeed', 'conveyorTransfer'].map(id => [id, normalizeRig(machinery[id])])
  ]);
  // The first-generation shipping fixture is single-cup only. Keep the source
  // files intact, but do not claim that tray/box assemblies ship in this runtime.
  rigs.shipMachine.content = { ids: ['product_cup_empty', 'product_cup_fill'], layer: 30,
    singleCup: machinery.shipMachine.content.singleCup };
  for (const [name, rig] of Object.entries(rigs)) for (const layer of rig.layers) {
    if (!assets[layer.id]) throw new Error('Rig references omitted runtime art: ' + name + '/' + layer.id);
    const asset = assets[layer.id], [, , w, h] = layer.rect;
    if (Math.abs((w / h) / (asset.width / asset.height) - 1) > 0.004) throw new Error('Nonuniform source assembly: ' + name + '/' + layer.id);
  }
  return { assets, rigs, entries };
}

export async function generateRuntimeArt(root) {
  const data = await readRuntimeArt(root);
  const source = "'use strict';\n// Generated by tools/art-build.mjs from reviewed art-source assemblies.\n" +
    '// Original artwork status/history is deliberately preserved in its source files.\n' +
    'const ART_ASSETS = ' + JSON.stringify(data.assets) + ';\n' +
    'const ART_RIGS = ' + JSON.stringify(data.rigs) + ';\n' +
    'const ART_RUNTIME_IDS = ' + JSON.stringify(FIRST_GENERATION_IDS) + ';\n' +
    'const ART_SOURCE_REFS = ' + JSON.stringify(ART_SOURCE_FILES) + ';\n' +
    'module.exports = { ART_ASSETS, ART_RIGS, ART_RUNTIME_IDS, ART_SOURCE_REFS };\n';
  await writeFile(path.join(root, 'src/art-manifest.js'), source);
  return data;
}

export async function copyRuntimeArt(root, targets, data) {
  const permitted = new Set(data.entries.map(entry => entry.path));
  for (const target of targets) {
    const outputRoot = contained(root, target);
    const artDir = contained(outputRoot, 'assets/art');
    // Prune only stale generated runtime art; never touch the source art tree.
    async function prune(directory) {
      let children;
      try { children = await readdir(directory, { withFileTypes: true }); }
      catch (error) { if (error.code === 'ENOENT') return; throw error; }
      for (const child of children) {
        const file = contained(artDir, path.relative(artDir, path.join(directory, child.name)));
        if (child.isSymbolicLink()) throw new Error('Symlink inside runtime art output');
        if (child.isDirectory()) await prune(file);
        else if (!permitted.has(path.relative(outputRoot, file).replaceAll('\\', '/'))) await unlink(file);
      }
    }
    await prune(artDir);
    for (const entry of data.entries) {
      const dest = contained(outputRoot, entry.path);
      await mkdir(path.dirname(dest), { recursive: true });
      if ((await lstat(path.dirname(dest))).isSymbolicLink()) throw new Error('Symlink in runtime art output');
      await copyFile(contained(root, entry.path), dest);
      const copied = await readFile(dest);
      if (createHash('sha256').update(copied).digest('hex') !== entry.sha256) throw new Error('Art copy mismatch: ' + entry.id);
    }
  }
  const packages = await Promise.all(targets.map(async target => {
    const runtimeFiles = target === 'web' ? ['index.html', 'game.bundle.js'] :
      ['game.js', 'game.json', 'project.config.json', 'config.js', 'game.bundle.js', ...['upgrade', 'machine', 'click', 'error'].map(id => 'audio/' + id + '.wav')];
    const entries = await Promise.all(runtimeFiles.map(async file => ({ path: file, bytes: (await lstat(contained(path.join(root, target), file))).size })));
    return { directory: target, verified: data.entries.length, missing: [], mismatched: [],
      otherRuntimeFiles: entries, totalRuntimeBytes: entries.reduce((sum, entry) => sum + entry.bytes, 0) + data.entries.reduce((sum, entry) => sum + entry.bytes, 0) };
  }));
  const report = { schemaVersion: 1, scope: 'first-generation-runtime-only', sourceFiles: ART_SOURCE_FILES,
    count: data.entries.length, compressedBytes: data.entries.reduce((sum, entry) => sum + entry.bytes, 0),
    decodedBytes: data.entries.reduce((sum, entry) => sum + entry.decodedBytes, 0),
    targets: packages,
    excluded: ['reference sheets', 'source images', 'factory_door', 'infeed belts', 'double tray', 'four-cup box', 'higher-generation machine art'],
    entries: data.entries };
  await mkdir(path.join(root, 'output/gen1-art-runtime'), { recursive: true });
  await writeFile(path.join(root, 'output/gen1-art-runtime/resource-report.json'), JSON.stringify(report, null, 2) + '\n');
  await writeFile(path.join(root, 'output/gen1-art-runtime/resource-report.md'),
    '# 首代运行资源体积与构建复制检查\n\n' +
    `运行 PNG：${report.count} 个；压缩文件 ${report.compressedBytes.toLocaleString('en-US')} bytes（${(report.compressedBytes / 1048576).toFixed(2)} MiB）；RGBA 解码估算 ${(report.decodedBytes / 1048576).toFixed(2)} MiB。\n\n` +
    packages.map(target => `- ${target.directory}：${report.count} 个资源逐文件 SHA-256 复制校验通过；包含代码、入口及该端音效的运行文件合计 ${(target.totalRuntimeBytes / 1048576).toFixed(2)} MiB。`).join('\n') +
    '\n\n本报告证明引用文件存在、PNG 尺寸与清单一致、双端文件完全一致；实际浏览器解码/加载结果另见正式入口运行验收。首代美术之外不作换肤完成承诺。\n');
  return report;
}
