import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateAudio } from './audio.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modules = new Map();
async function collect(file) {
  const id = path.relative(root, file).replaceAll('\\', '/');
  if (modules.has(id)) return id;
  modules.set(id, '');
  let source = await readFile(file, 'utf8');
  const requires = [...source.matchAll(/require\(['"](\.\.?\/[^'"]+)['"]\)/g)];
  for (const match of requires) {
    const dependency = path.resolve(path.dirname(file), match[1].endsWith('.js') ? match[1] : match[1] + '.js');
    if (!dependency.startsWith(root + path.sep)) throw new Error('Dependency outside project');
    const dependencyId = await collect(dependency);
    source = source.replace(match[0], `require(${JSON.stringify(dependencyId)})`);
  }
  modules.set(id, source);
  return id;
}
const entry = await collect(path.join(root, 'src/main.js'));
const bundle = `/* 小小爆米花厂 v1.0 | generated by npm run build */\n(function(){\n'use strict';\nconst modules={${[...modules].map(([id, source]) => `${JSON.stringify(id)}:function(module,exports,require){\n${source}\n}`).join(',\n')}};\nconst cache={}; function require(id){if(cache[id])return cache[id].exports;if(!modules[id])throw new Error('Unknown module '+id);const m=cache[id]={exports:{}};modules[id](m,m.exports,require);return m.exports;} require(${JSON.stringify(entry)});\n})();\n`;
await mkdir(path.join(root, 'build/douyin'), { recursive: true });
await mkdir(path.join(root, 'web'), { recursive: true });
await writeFile(path.join(root, 'web/game.bundle.js'), bundle);
await writeFile(path.join(root, 'build/douyin/game.bundle.js'), bundle);
await writeFile(path.join(root, 'build/douyin/game.js'), "require('./config.js');\nrequire('./game.bundle.js');\n");
await writeFile(path.join(root, 'build/douyin/game.json'), JSON.stringify({ deviceOrientation: 'portrait', showStatusBar: false }, null, 2));
let config = {appId:'',rewardAdUnitId:'',interstitialAdUnitId:'',allowSimulatedAds:false};
try { config = {...config,...JSON.parse(await readFile(path.join(root,'config.local.json'),'utf8'))}; }
catch(error) { if(error.code!=='ENOENT')throw new Error('config.local.json 无效: '+error.message); }
config.allowSimulatedAds=false;
await writeFile(path.join(root, 'build/douyin/config.js'), '(typeof globalThis !== "undefined" ? globalThis : GameGlobal).POPCORN_CONFIG = '+JSON.stringify(config,null,2)+';\n');
await writeFile(path.join(root, 'build/douyin/project.config.json'), JSON.stringify({ description: '小小爆米花厂', setting: { es6: true, minified: false, urlCheck: true }, appid: config.appId, projectname: 'tiny-popcorn-factory', compileType: 'game' }, null, 2));
await generateAudio(path.join(root,'build/douyin/audio'));
console.log(`Built ${modules.size} modules; ${(Buffer.byteLength(bundle)/1024).toFixed(1)} KiB. Web: web/ · Douyin: build/douyin/`);
